In [7]:
from dataset import JetDataSet
from torch.utils.data import DataLoader
from train import build_dataloader
from tqdm import tqdm

In [ ]:
data_loader = DataLoader(JetDataSet(
    data_dir = "/hpcwork/rwth0934/hep_foundation_model/preprocessed_data/TTBar_train_processed.h5",
    tag = "train",
    num_features=3,
    num_bins=(40, 30, 30),
    num_const=10,
    add_stop=True,
    add_start=True,
    n_jets=100,
    key = "discretized",
    ),
    batch_size = 10,
    shuffle= True, # optimization
    num_workers=4,            
    pin_memory=True,
    persistent_workers=True,
    prefetch_factor=4,)

Loading Dataset: train | n_jets = 100 | /hpcwork/rwth0934/hep_foundation_model/preprocessed_data/TTBar_train_processed.h5


In [ ]:
for epoch in range(10):
    progress_bar = tqdm(
            data_loader,
            desc = f"Epoch {epoch+1}/{10} [Training]",
            leave = True
    )
    for x in progress_bar:
        print(x)

        



Epoch 1/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 77.39it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 2/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 433.26it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 3/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 433.96it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 4/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 446.89it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 5/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 468.07it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 6/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 543.13it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 7/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 459.22it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 8/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 485.72it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 9/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 473.81it/s]


tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 10/10 [Training]:   0%|          | 0/10 [00:00<?, ?it/s]

tensor([[[ 0,  0,  0],
         [26, 20, 17],
         [26, 20, 17],
         [25, 21, 16],
         [22, 22, 17],
         [20, 13,  5],
         [20, 21, 16],
         [19,  9, 19],
         [19, 13,  3],
         [19, 21, 17],
         [19, 21, 16]],

        [[ 0,  0,  0],
         [30, 10, 15],
         [24, 18, 22],
         [23, 18, 21],
         [23, 17, 22],
         [23, 17,  9],
         [22, 18, 22],
         [22, 17, 23],
         [21, 10, 15],
         [20, 10, 15],
         [20, 17,  9]],

        [[ 0,  0,  0],
         [36, 17, 15],
         [27, 16, 18],
         [27, 16, 18],
         [26, 16, 18],
         [25, 17, 15],
         [24, 16, 19],
         [24, 13, 14],
         [23, 16, 18],
         [23, 17, 18],
         [23, 17, 15]],

        [[ 0,  0,  0],
         [33, 15, 13],
         [29, 17, 21],
         [28, 17, 21],
         [27, 15, 14],
         [26, 15, 16],
         [26, 15, 14],
         [25, 18, 20],
         [24, 18, 21],
         [22, 15, 18],
     

Epoch 10/10 [Training]: 100%|██████████| 10/10 [00:00<00:00, 413.47it/s]


tensor([[[ 0,  0,  0],
         [36, 16, 17],
         [30, 16, 17],
         [23, 16, 17],
         [22, 19, 17],
         [22, 16, 17],
         [22, 12, 11],
         [21, 12, 10],
         [21, 12,  9],
         [20, 12, 10],
         [20, 16, 17]],

        [[ 0,  0,  0],
         [30, 18, 15],
         [27, 17, 15],
         [26, 18, 15],
         [23, 17, 16],
         [22, 15, 14],
         [19, 13, 14],
         [19, 18, 16],
         [19, 10, 24],
         [19, 11, 24],
         [19, 18, 15]],

        [[ 0,  0,  0],
         [32, 17, 17],
         [29, 17, 17],
         [28, 17, 17],
         [28, 15, 16],
         [24, 15, 15],
         [22, 18, 17],
         [20, 17, 17],
         [20, 18,  3],
         [19, 17, 17],
         [19, 19,  4]],

        [[ 0,  0,  0],
         [27, 18, 18],
         [26, 19, 18],
         [26, 19, 19],
         [23, 19, 15],
         [23, 19, 19],
         [22, 18, 18],
         [22, 19, 14],
         [22, 19, 14],
         [22, 18, 18],
     

: 